name: flutter_tiketkonser
description: Aplikasi Pembelian Tiket Event/Konser dengan GetX
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/confetti1.jpg
  
  # Fonts
  fonts:
    - family: Chilanka
      fonts:
        - asset: assets/fonts/Chilanka-Regular.ttf